### ISSUE TITLE
In dark mode, the text in the input box will be the same color as the background of the input box

### ISSUE THREAD

**Issue by haitang000** [ZapNotesApp/Zap#17]
![image](https://github.com/user-attachments/assets/2335585b-42bd-4d8b-bfcd-e11ae594ee73)

**Comment by ZigaoWang** [comment]
Thank you for your feedback, fixing it right now!

**Comment by ZigaoWang** [comment]
fixed!

**Comment by haitang000** [comment]
> fixed!

Thanks
