### ISSUE TITLE
There is a chance that using the AI summary function will cause the photo note to disappear.

### ISSUE THREAD

**Issue by haitang000** [ZapNotesApp/Zap#18]
_(Not sure if this issue will appear on other devices)_

**The device I use:** iPhone 13 Pro
**Current system version:** iOS 18.1

https://github.com/user-attachments/assets/e692f559-30bd-4426-8a69-e6d7f77d5e9c

_At times, after clicking the AI summary, the image in the photo note will be summarized into text by the AI, and the image will also disappear._

**Comment by ZigaoWang** [comment]
Let me check that out, by the way, are you Chinese? Any chance that we can speak Chinese so that it will be easier?

**Comment by haitang000** [comment]
> Let me check that out, by the way, are you Chinese? Any chance that we can speak Chinese so that it will be easier?

ok

**Comment by ZigaoWang** [comment]
ahhh 我知道了，我这边也是这样，真服了，我以前修过这个，后来又来了

**Comment by haitang000** [comment]
> ahhh 我知道了，我这边也是这样，真服了，我以前修过这个，后来又来了

emm，你或许可以加 AI 总结类型的设置，比如加几个开关，让 ai 不总结某些类型的内容

**Comment by ZigaoWang** [comment]
好主意！我过一会再修吧！这个挺复杂的，你要是能帮我看看也行，谢谢！

**Comment by haitang000** [comment]
> 好主意！我过一会再修吧！这个挺复杂的，你要是能帮我看看也行，谢谢！

我不会 Swift qwq，我只是个写网页前端的 qwq，没法帮到你 qwq

**Comment by ZigaoWang** [comment]
没事我一开始也是只会前端，然后后面我花了两周自己学的

**Comment by ZigaoWang** [comment]
我知道了！
HTTP Status Code: 200
Response Headers: [AnyHashable("Server"): nginx, AnyHashable("Etag"): W/"48d-efYItuO7KsX2P3QgMm4T6ZhZfxg", AnyHashable("Date"): Mon, 18 Nov 2024 06:07:36 GMT, AnyHashable("x-dns-prefetch-control"): off, AnyHashable("content-security-policy"): default-src 'self';base-uri 'self';font-src 'self' https: data:;form-action 'self';frame-ancestors 'self';img-src 'self' data:;object-src 'none';script-src 'self';script-src-attr 'none';style-src 'self' https: 'unsafe-inline';upgrade-insecure-requests, AnyHashable("Content-Type"): application/json; charset=utf-8, AnyHashable("cross-origin-resource-policy"): same-origin, AnyHashable("x-xss-protection"): 0, AnyHashable("x-frame-options"): SAMEORIGIN, AnyHashable("cross-origin-opener-policy"): same-origin, AnyHashable("Content-Length"): 1165, AnyHashable("x-download-options"): noopen, AnyHashable("Strict-Transport-Security"): max-age=31536000; includeSubDomains, AnyHashable("referrer-policy"): no-referrer, AnyHashable("origin-agent-cluster"): ?1, AnyHashable("x-permitted-cross-domain-policies"): none, AnyHashable("x-content-type-options"): nosniff]
Error decoding JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '`' around line 1, column 1." UserInfo={NSJSONSerializationErrorIndex=0, NSDebugDescription=Unexpected character '`' around line 1, column 1.})))

**Comment by ZigaoWang** [comment]
其实代码是没问题的，但是 ai 给出的回复不是 json 格式，就清空了

**Comment by ZigaoWang** [comment]
我把 ai 的 prompt 改进一下

**Comment by ZigaoWang** [comment]
你现在试一下？
不在 testflight 上，我等会上传

**Comment by haitang000** [comment]
> 你现在试一下？
> 
> 不在 testflight 上，我等会上传

谢谢 qwq，问题已解决
