### ISSUE TITLE
对于添加笔记功能的优化

### ISSUE THREAD

**Issue by haitang000** [ZapNotesApp/Zap#19]
1. 在支持通过滑动圆盘选择笔记类型的同时，支持通过点击选择类型而并非仅仅支持滑动

_（一个圆盘就放在那里的话可能有些意义不明，多数用户会本能地去点击而并非滑动）_

---

2. 为圆盘添加轻微的背景模糊

_（参考微信底部导航栏）_

![image](https://github.com/user-attachments/assets/7dbc6a26-cc1b-432a-85ef-846f65fe650b)

**Comment by ZigaoWang** [comment]
谢谢回复！

很好笑的是我原来用的是四个最简单的按钮，然后后面有点无聊，就做了这个滑动的东西，现在就觉得还是原来的按钮好，所以我在尝试两个都保留，然后在设置里面选择一个横向的滑动，那也可以点击的一种模式

**Comment by ZigaoWang** [comment]
解决了你看看可不可以
