### ISSUE TITLE
[不太重要][XL][国际化] 增加对中文的支持

### ISSUE THREAD

**Issue by haitang000** [ZapNotesApp/Zap#21]
> 可以在项目完善后再加 qwq

**Comment by ZigaoWang** [comment]
哈哈哈又是你！谢谢
我在后面几天加一下
我没什么想法怎么做，因为逻辑是把新的替代原来的，可以试试复制一份，然后滚回

**Comment by haitang000** [comment]
>  哈哈哈又是你！谢谢
> 
> 我在后面几天加一下
> 
> 我没什么想法怎么做，因为逻辑是把新的替代原来的，可以试试复制一份，然后滚回

以 JS 的思路去写的话可能就是给所有文字打上 ID，然后一个一个 innerHTML，不知道这个思路在 SwiftUI 里面能不能实行 qwq

**Comment by ZigaoWang** [comment]
ok 我等会试试，谢谢啦

**Comment by haitang000** [comment]
我发现我这个思路有点太蠢了（
看到了别人用的 dom 替换（

**Comment by ZigaoWang** [comment]
https://github.com/ZigaoWang/elevate-ai
在做这个，等会过来，挺帅的，后面你可以帮我试试哈哈哈哈

**Comment by haitang000** [comment]
> https://github.com/ZigaoWang/elevate-ai
> 
> 在做这个，等会过来，挺帅的，后面你可以帮我试试哈哈哈哈

周末 clone 下来玩玩（）

**Comment by ZigaoWang** [comment]
我在学 localization，后面几天有空加

**Comment by ZigaoWang** [comment]
哦对了你想要加入我们团队吗？你就当测试官？我本来真的没什么动力做下去了，因为做的有点差，现在有很多动力，因为有你！
你要不加一下我微信？这边说不太方便，你要不邮件我你的微信号？我的邮件：a@zigao.wang
谢谢！

**Comment by ZigaoWang** [comment]
添加好了，需要将系统语音设置为中文。我后面可以加一个功能，在设置里面单独设置语言。

**Comment by ZigaoWang** [comment]
![CleanShot 2024-12-29 at 13 13 29@2x](https://github.com/user-attachments/assets/3f62d6fa-1200-430a-856b-5e9501a87685)
![CleanShot 2024-12-29 at 13 13 34@2x](https://github.com/user-attachments/assets/25acbf3b-3fcc-4f6c-8905-75c79c9809e2)
![CleanShot 2024-12-29 at 13 13 38@2x](https://github.com/user-attachments/assets/a8e2b2b2-8c75-4f24-b596-5e322f3036f1)
![CleanShot 2024-12-29 at 13 13 48@2x](https://github.com/user-attachments/assets/74a1d3fc-effa-42fb-a4f6-880bf69c4e71)

**Comment by haitang000** [comment]
> 哦对了你想要加入我们团队吗？你就当测试官？我本来真的没什么动力做下去了，因为做的有点差，现在有很多动力，因为有你！
> 
> 你要不加一下我微信？这边说不太方便，你要不邮件我你的微信号？我的邮件：a@zigao.wang
> 
> 谢谢！

ok

**Comment by haitang000** [comment]
٩(•̤̀ᵕ•̤́๑)ᵒᵏ
