### ISSUE TITLE
[急][M][BUG] AI 总结后导致笔记全部消失

### ISSUE THREAD

**Issue by haitang000** [ZapNotesApp/Zap#23]
**出现问题的设备:** iPad 9
**系统版本:** iPadOS 18.2

_不确定该问题是否会在 iPhone 上出现，需要进一步复现问题_

**Comment by ZigaoWang** [comment]
Error decoding JSON: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected character '`' around line 1, column 1." UserInfo={NSJSONSerializationErrorIndex=0, NSDebugDescription=Unexpected character '`' around line 1, column 1.})))

**Comment by ZigaoWang** [comment]
还是这个的货，没有解出来 json，就会消失
