### ISSUE TITLE
[较为重要][M][BUG] 无法删除在图片笔记之上的音频笔记

### ISSUE THREAD

**Issue by haitang000** [ZapNotesApp/Zap#24]
**出现问题的设备:** iPhone 13 Pro
**系统版本:** iOS 18.2
**软件版本:** Build 2.3.13

**问题状况:** 当一个音频笔记在图片笔记上时，点击删除键会打开下方图片笔记的预览且不会删除音频笔记

https://github.com/user-attachments/assets/3bf7cce8-5663-4dd4-8ad1-93aacd976be3

_(该问题仅在该设备上出现过，可能需要在其他型号/系统版本的设备上继续测试)_

**Comment by ZigaoWang** [comment]
解决了，是因为图片 z-axis 过高导致覆盖了别的按钮。谢谢！

**Comment by ZigaoWang** [comment]
我提交的版本是 v2.3.13 build 3，我忘改到 v2.3.14 了，但这样就可以直接通过，你看一下，有可能需要手动更新，新的版本图片会变高，就是展示全图而不是一部分，所以更新很明显。像这样：

![CleanShot 2024-12-29 at 10 34 32@2x](https://github.com/user-attachments/assets/7ad7ee50-9914-4b07-a52e-0d929bd3fff8)

还是谢谢你的帮助！我最后一定会把你加到感谢人员里的！
